title: Beckham Kunkler
description: Beckham is a senior at San Dieguito Academy, and loves his classes in Biology and Music. He is currently in 3 different ensembles playing both piano and bassoon
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
